// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server_central.proto

#include "server_central.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rpc_server {

inline constexpr UnregisterServerRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UnregisterServerRes::UnregisterServerRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UnregisterServerResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnregisterServerResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnregisterServerResDefaultTypeInternal() {}
  union {
    UnregisterServerRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnregisterServerResDefaultTypeInternal _UnregisterServerRes_default_instance_;

inline constexpr UnregisterServerReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        server_type_{static_cast< ::rpc_server::ServerType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UnregisterServerReq::UnregisterServerReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UnregisterServerReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnregisterServerReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnregisterServerReqDefaultTypeInternal() {}
  union {
    UnregisterServerReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnregisterServerReqDefaultTypeInternal _UnregisterServerReq_default_instance_;

inline constexpr RegisterServerRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RegisterServerRes::RegisterServerRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RegisterServerResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterServerResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterServerResDefaultTypeInternal() {}
  union {
    RegisterServerRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterServerResDefaultTypeInternal _RegisterServerRes_default_instance_;

inline constexpr RegisterServerReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        server_type_{static_cast< ::rpc_server::ServerType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RegisterServerReq::RegisterServerReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RegisterServerReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterServerReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterServerReqDefaultTypeInternal() {}
  union {
    RegisterServerReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterServerReqDefaultTypeInternal _RegisterServerReq_default_instance_;

inline constexpr HeartbeatRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HeartbeatRes::HeartbeatRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HeartbeatResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatResDefaultTypeInternal() {}
  union {
    HeartbeatRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatResDefaultTypeInternal _HeartbeatRes_default_instance_;

inline constexpr HeartbeatReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        server_type_{static_cast< ::rpc_server::ServerType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR HeartbeatReq::HeartbeatReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HeartbeatReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatReqDefaultTypeInternal() {}
  union {
    HeartbeatReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatReqDefaultTypeInternal _HeartbeatReq_default_instance_;

inline constexpr ConnectPoorReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : server_type_{static_cast< ::rpc_server::ServerType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConnectPoorReq::ConnectPoorReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConnectPoorReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConnectPoorReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConnectPoorReqDefaultTypeInternal() {}
  union {
    ConnectPoorReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConnectPoorReqDefaultTypeInternal _ConnectPoorReq_default_instance_;

inline constexpr ConnectInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConnectInfo::ConnectInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConnectInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConnectInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConnectInfoDefaultTypeInternal() {}
  union {
    ConnectInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConnectInfoDefaultTypeInternal _ConnectInfo_default_instance_;

inline constexpr ConnectPoorRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : connect_info_{},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConnectPoorRes::ConnectPoorRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ConnectPoorResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConnectPoorResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConnectPoorResDefaultTypeInternal() {}
  union {
    ConnectPoorRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConnectPoorResDefaultTypeInternal _ConnectPoorRes_default_instance_;
}  // namespace rpc_server
static ::_pb::Metadata file_level_metadata_server_5fcentral_2eproto[9];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_server_5fcentral_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_5fcentral_2eproto = nullptr;
const ::uint32_t TableStruct_server_5fcentral_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerReq, _impl_.server_type_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerReq, _impl_.address_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerReq, _impl_.port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerRes, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::RegisterServerRes, _impl_.message_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerReq, _impl_.server_type_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerReq, _impl_.address_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerReq, _impl_.port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerRes, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::UnregisterServerRes, _impl_.message_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectPoorReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectPoorReq, _impl_.server_type_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectPoorRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectPoorRes, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectPoorRes, _impl_.connect_info_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectPoorRes, _impl_.message_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectInfo, _impl_.address_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::ConnectInfo, _impl_.port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatReq, _impl_.server_type_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatReq, _impl_.address_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatReq, _impl_.port_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatRes, _impl_.success_),
    PROTOBUF_FIELD_OFFSET(::rpc_server::HeartbeatRes, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::rpc_server::RegisterServerReq)},
        {11, -1, -1, sizeof(::rpc_server::RegisterServerRes)},
        {21, -1, -1, sizeof(::rpc_server::UnregisterServerReq)},
        {32, -1, -1, sizeof(::rpc_server::UnregisterServerRes)},
        {42, -1, -1, sizeof(::rpc_server::ConnectPoorReq)},
        {51, -1, -1, sizeof(::rpc_server::ConnectPoorRes)},
        {62, -1, -1, sizeof(::rpc_server::ConnectInfo)},
        {72, -1, -1, sizeof(::rpc_server::HeartbeatReq)},
        {83, -1, -1, sizeof(::rpc_server::HeartbeatRes)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::rpc_server::_RegisterServerReq_default_instance_._instance,
    &::rpc_server::_RegisterServerRes_default_instance_._instance,
    &::rpc_server::_UnregisterServerReq_default_instance_._instance,
    &::rpc_server::_UnregisterServerRes_default_instance_._instance,
    &::rpc_server::_ConnectPoorReq_default_instance_._instance,
    &::rpc_server::_ConnectPoorRes_default_instance_._instance,
    &::rpc_server::_ConnectInfo_default_instance_._instance,
    &::rpc_server::_HeartbeatReq_default_instance_._instance,
    &::rpc_server::_HeartbeatRes_default_instance_._instance,
};
const char descriptor_table_protodef_server_5fcentral_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\024server_central.proto\022\nrpc_server\"_\n\021Re"
    "gisterServerReq\022+\n\013server_type\030\001 \001(\0162\026.r"
    "pc_server.ServerType\022\017\n\007address\030\002 \001(\t\022\014\n"
    "\004port\030\003 \001(\t\"5\n\021RegisterServerRes\022\017\n\007succ"
    "ess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"a\n\023Unregister"
    "ServerReq\022+\n\013server_type\030\001 \001(\0162\026.rpc_ser"
    "ver.ServerType\022\017\n\007address\030\002 \001(\t\022\014\n\004port\030"
    "\003 \001(\t\"7\n\023UnregisterServerRes\022\017\n\007success\030"
    "\001 \001(\010\022\017\n\007message\030\002 \001(\t\"=\n\016ConnectPoorReq"
    "\022+\n\013server_type\030\001 \001(\0162\026.rpc_server.Serve"
    "rType\"a\n\016ConnectPoorRes\022\017\n\007success\030\001 \001(\010"
    "\022-\n\014connect_info\030\002 \003(\0132\027.rpc_server.Conn"
    "ectInfo\022\017\n\007message\030\003 \001(\t\",\n\013ConnectInfo\022"
    "\017\n\007address\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\"Z\n\014Heartb"
    "eatReq\022+\n\013server_type\030\001 \001(\0162\026.rpc_server"
    ".ServerType\022\017\n\007address\030\002 \001(\t\022\014\n\004port\030\003 \001"
    "(\t\"0\n\014HeartbeatRes\022\017\n\007success\030\001 \001(\010\022\017\n\007m"
    "essage\030\002 \001(\t*S\n\nServerType\022\013\n\007UNKNOWN\020\000\022"
    "\013\n\007CENTRAL\020\001\022\010\n\004DATA\020\002\022\013\n\007GATEWAY\020\003\022\t\n\005L"
    "OGIN\020\004\022\t\n\005LOGIC\020\0052\303\002\n\rCentralServer\022O\n\017R"
    "egister_server\022\035.rpc_server.RegisterServ"
    "erReq\032\035.rpc_server.RegisterServerRes\022U\n\021"
    "Unregister_server\022\037.rpc_server.Unregiste"
    "rServerReq\032\037.rpc_server.UnregisterServer"
    "Res\022I\n\017Get_connec_poor\022\032.rpc_server.Conn"
    "ectPoorReq\032\032.rpc_server.ConnectPoorRes\022\?"
    "\n\tHeartbeat\022\030.rpc_server.HeartbeatReq\032\030."
    "rpc_server.HeartbeatResb\006proto3"
};
static ::absl::once_flag descriptor_table_server_5fcentral_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_server_5fcentral_2eproto = {
    false,
    false,
    1111,
    descriptor_table_protodef_server_5fcentral_2eproto,
    "server_central.proto",
    &descriptor_table_server_5fcentral_2eproto_once,
    nullptr,
    0,
    9,
    schemas,
    file_default_instances,
    TableStruct_server_5fcentral_2eproto::offsets,
    file_level_metadata_server_5fcentral_2eproto,
    file_level_enum_descriptors_server_5fcentral_2eproto,
    file_level_service_descriptors_server_5fcentral_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_server_5fcentral_2eproto_getter() {
  return &descriptor_table_server_5fcentral_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_server_5fcentral_2eproto(&descriptor_table_server_5fcentral_2eproto);
namespace rpc_server {
const ::google::protobuf::EnumDescriptor* ServerType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_server_5fcentral_2eproto);
  return file_level_enum_descriptors_server_5fcentral_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ServerType_internal_data_[] = {
    393216u, 0u, };
bool ServerType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// ===================================================================

class RegisterServerReq::_Internal {
 public:
};

RegisterServerReq::RegisterServerReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.RegisterServerReq)
}
inline PROTOBUF_NDEBUG_INLINE RegisterServerReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : address_(arena, from.address_),
        port_(arena, from.port_),
        _cached_size_{0} {}

RegisterServerReq::RegisterServerReq(
    ::google::protobuf::Arena* arena,
    const RegisterServerReq& from)
    : ::google::protobuf::Message(arena) {
  RegisterServerReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.server_type_ = from._impl_.server_type_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.RegisterServerReq)
}
inline PROTOBUF_NDEBUG_INLINE RegisterServerReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        port_(arena),
        _cached_size_{0} {}

inline void RegisterServerReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.server_type_ = {};
}
RegisterServerReq::~RegisterServerReq() {
  // @@protoc_insertion_point(destructor:rpc_server.RegisterServerReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterServerReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.port_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RegisterServerReq::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.RegisterServerReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  _impl_.server_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterServerReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 48, 2> RegisterServerReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterServerReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rpc_server.ServerType server_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RegisterServerReq, _impl_.server_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterServerReq, _impl_.server_type_)}},
    // string address = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterServerReq, _impl_.address_)}},
    // string port = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterServerReq, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rpc_server.ServerType server_type = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterServerReq, _impl_.server_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string address = 2;
    {PROTOBUF_FIELD_OFFSET(RegisterServerReq, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string port = 3;
    {PROTOBUF_FIELD_OFFSET(RegisterServerReq, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\7\4\0\0\0\0"
    "rpc_server.RegisterServerReq"
    "address"
    "port"
  }},
};

::uint8_t* RegisterServerReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.RegisterServerReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_server_type(), target);
  }

  // string address = 2;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.RegisterServerReq.address");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string port = 3;
  if (!this->_internal_port().empty()) {
    const std::string& _s = this->_internal_port();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.RegisterServerReq.port");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.RegisterServerReq)
  return target;
}

::size_t RegisterServerReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.RegisterServerReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string address = 2;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  // string port = 3;
  if (!this->_internal_port().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_port());
  }

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_server_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterServerReq::_class_data_ = {
    RegisterServerReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RegisterServerReq::GetClassData() const {
  return &_class_data_;
}

void RegisterServerReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterServerReq*>(&to_msg);
  auto& from = static_cast<const RegisterServerReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.RegisterServerReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_server_type() != 0) {
    _this->_internal_set_server_type(from._internal_server_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterServerReq::CopyFrom(const RegisterServerReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.RegisterServerReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterServerReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RegisterServerReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RegisterServerReq::InternalSwap(RegisterServerReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
  swap(_impl_.server_type_, other->_impl_.server_type_);
}

::google::protobuf::Metadata RegisterServerReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[0]);
}
// ===================================================================

class RegisterServerRes::_Internal {
 public:
};

RegisterServerRes::RegisterServerRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.RegisterServerRes)
}
inline PROTOBUF_NDEBUG_INLINE RegisterServerRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

RegisterServerRes::RegisterServerRes(
    ::google::protobuf::Arena* arena,
    const RegisterServerRes& from)
    : ::google::protobuf::Message(arena) {
  RegisterServerRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.RegisterServerRes)
}
inline PROTOBUF_NDEBUG_INLINE RegisterServerRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void RegisterServerRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
RegisterServerRes::~RegisterServerRes() {
  // @@protoc_insertion_point(destructor:rpc_server.RegisterServerRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RegisterServerRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RegisterServerRes::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.RegisterServerRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RegisterServerRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> RegisterServerRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RegisterServerRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterServerRes, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RegisterServerRes, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RegisterServerRes, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(RegisterServerRes, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(RegisterServerRes, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\7\0\0\0\0\0"
    "rpc_server.RegisterServerRes"
    "message"
  }},
};

::uint8_t* RegisterServerRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.RegisterServerRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.RegisterServerRes.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.RegisterServerRes)
  return target;
}

::size_t RegisterServerRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.RegisterServerRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RegisterServerRes::_class_data_ = {
    RegisterServerRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RegisterServerRes::GetClassData() const {
  return &_class_data_;
}

void RegisterServerRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RegisterServerRes*>(&to_msg);
  auto& from = static_cast<const RegisterServerRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.RegisterServerRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterServerRes::CopyFrom(const RegisterServerRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.RegisterServerRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RegisterServerRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RegisterServerRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RegisterServerRes::InternalSwap(RegisterServerRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata RegisterServerRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[1]);
}
// ===================================================================

class UnregisterServerReq::_Internal {
 public:
};

UnregisterServerReq::UnregisterServerReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.UnregisterServerReq)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterServerReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : address_(arena, from.address_),
        port_(arena, from.port_),
        _cached_size_{0} {}

UnregisterServerReq::UnregisterServerReq(
    ::google::protobuf::Arena* arena,
    const UnregisterServerReq& from)
    : ::google::protobuf::Message(arena) {
  UnregisterServerReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.server_type_ = from._impl_.server_type_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.UnregisterServerReq)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterServerReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        port_(arena),
        _cached_size_{0} {}

inline void UnregisterServerReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.server_type_ = {};
}
UnregisterServerReq::~UnregisterServerReq() {
  // @@protoc_insertion_point(destructor:rpc_server.UnregisterServerReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UnregisterServerReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.port_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UnregisterServerReq::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.UnregisterServerReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  _impl_.server_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UnregisterServerReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 50, 2> UnregisterServerReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UnregisterServerReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rpc_server.ServerType server_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UnregisterServerReq, _impl_.server_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterServerReq, _impl_.server_type_)}},
    // string address = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterServerReq, _impl_.address_)}},
    // string port = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterServerReq, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rpc_server.ServerType server_type = 1;
    {PROTOBUF_FIELD_OFFSET(UnregisterServerReq, _impl_.server_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string address = 2;
    {PROTOBUF_FIELD_OFFSET(UnregisterServerReq, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string port = 3;
    {PROTOBUF_FIELD_OFFSET(UnregisterServerReq, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\7\4\0\0\0\0"
    "rpc_server.UnregisterServerReq"
    "address"
    "port"
  }},
};

::uint8_t* UnregisterServerReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.UnregisterServerReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_server_type(), target);
  }

  // string address = 2;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.UnregisterServerReq.address");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string port = 3;
  if (!this->_internal_port().empty()) {
    const std::string& _s = this->_internal_port();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.UnregisterServerReq.port");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.UnregisterServerReq)
  return target;
}

::size_t UnregisterServerReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.UnregisterServerReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string address = 2;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  // string port = 3;
  if (!this->_internal_port().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_port());
  }

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_server_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UnregisterServerReq::_class_data_ = {
    UnregisterServerReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UnregisterServerReq::GetClassData() const {
  return &_class_data_;
}

void UnregisterServerReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UnregisterServerReq*>(&to_msg);
  auto& from = static_cast<const UnregisterServerReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.UnregisterServerReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_server_type() != 0) {
    _this->_internal_set_server_type(from._internal_server_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UnregisterServerReq::CopyFrom(const UnregisterServerReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.UnregisterServerReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UnregisterServerReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UnregisterServerReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UnregisterServerReq::InternalSwap(UnregisterServerReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
  swap(_impl_.server_type_, other->_impl_.server_type_);
}

::google::protobuf::Metadata UnregisterServerReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[2]);
}
// ===================================================================

class UnregisterServerRes::_Internal {
 public:
};

UnregisterServerRes::UnregisterServerRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.UnregisterServerRes)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterServerRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UnregisterServerRes::UnregisterServerRes(
    ::google::protobuf::Arena* arena,
    const UnregisterServerRes& from)
    : ::google::protobuf::Message(arena) {
  UnregisterServerRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.UnregisterServerRes)
}
inline PROTOBUF_NDEBUG_INLINE UnregisterServerRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UnregisterServerRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
UnregisterServerRes::~UnregisterServerRes() {
  // @@protoc_insertion_point(destructor:rpc_server.UnregisterServerRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UnregisterServerRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UnregisterServerRes::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.UnregisterServerRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UnregisterServerRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 46, 2> UnregisterServerRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UnregisterServerRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterServerRes, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UnregisterServerRes, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UnregisterServerRes, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(UnregisterServerRes, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(UnregisterServerRes, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\7\0\0\0\0\0"
    "rpc_server.UnregisterServerRes"
    "message"
  }},
};

::uint8_t* UnregisterServerRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.UnregisterServerRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.UnregisterServerRes.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.UnregisterServerRes)
  return target;
}

::size_t UnregisterServerRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.UnregisterServerRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UnregisterServerRes::_class_data_ = {
    UnregisterServerRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UnregisterServerRes::GetClassData() const {
  return &_class_data_;
}

void UnregisterServerRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UnregisterServerRes*>(&to_msg);
  auto& from = static_cast<const UnregisterServerRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.UnregisterServerRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UnregisterServerRes::CopyFrom(const UnregisterServerRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.UnregisterServerRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UnregisterServerRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UnregisterServerRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UnregisterServerRes::InternalSwap(UnregisterServerRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata UnregisterServerRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[3]);
}
// ===================================================================

class ConnectPoorReq::_Internal {
 public:
};

ConnectPoorReq::ConnectPoorReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.ConnectPoorReq)
}
ConnectPoorReq::ConnectPoorReq(
    ::google::protobuf::Arena* arena, const ConnectPoorReq& from)
    : ConnectPoorReq(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ConnectPoorReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ConnectPoorReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.server_type_ = {};
}
ConnectPoorReq::~ConnectPoorReq() {
  // @@protoc_insertion_point(destructor:rpc_server.ConnectPoorReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConnectPoorReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ConnectPoorReq::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.ConnectPoorReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.server_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConnectPoorReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ConnectPoorReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ConnectPoorReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .rpc_server.ServerType server_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConnectPoorReq, _impl_.server_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectPoorReq, _impl_.server_type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rpc_server.ServerType server_type = 1;
    {PROTOBUF_FIELD_OFFSET(ConnectPoorReq, _impl_.server_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ConnectPoorReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.ConnectPoorReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_server_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.ConnectPoorReq)
  return target;
}

::size_t ConnectPoorReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.ConnectPoorReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_server_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ConnectPoorReq::_class_data_ = {
    ConnectPoorReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ConnectPoorReq::GetClassData() const {
  return &_class_data_;
}

void ConnectPoorReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ConnectPoorReq*>(&to_msg);
  auto& from = static_cast<const ConnectPoorReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.ConnectPoorReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_server_type() != 0) {
    _this->_internal_set_server_type(from._internal_server_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConnectPoorReq::CopyFrom(const ConnectPoorReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.ConnectPoorReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConnectPoorReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ConnectPoorReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ConnectPoorReq::InternalSwap(ConnectPoorReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.server_type_, other->_impl_.server_type_);
}

::google::protobuf::Metadata ConnectPoorReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[4]);
}
// ===================================================================

class ConnectPoorRes::_Internal {
 public:
};

ConnectPoorRes::ConnectPoorRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.ConnectPoorRes)
}
inline PROTOBUF_NDEBUG_INLINE ConnectPoorRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : connect_info_{visibility, arena, from.connect_info_},
        message_(arena, from.message_),
        _cached_size_{0} {}

ConnectPoorRes::ConnectPoorRes(
    ::google::protobuf::Arena* arena,
    const ConnectPoorRes& from)
    : ::google::protobuf::Message(arena) {
  ConnectPoorRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.ConnectPoorRes)
}
inline PROTOBUF_NDEBUG_INLINE ConnectPoorRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : connect_info_{visibility, arena},
        message_(arena),
        _cached_size_{0} {}

inline void ConnectPoorRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
ConnectPoorRes::~ConnectPoorRes() {
  // @@protoc_insertion_point(destructor:rpc_server.ConnectPoorRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConnectPoorRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ConnectPoorRes::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.ConnectPoorRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.connect_info_.Clear();
  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConnectPoorRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 41, 2> ConnectPoorRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ConnectPoorRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ConnectPoorRes, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectPoorRes, _impl_.success_)}},
    // repeated .rpc_server.ConnectInfo connect_info = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectPoorRes, _impl_.connect_info_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectPoorRes, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(ConnectPoorRes, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated .rpc_server.ConnectInfo connect_info = 2;
    {PROTOBUF_FIELD_OFFSET(ConnectPoorRes, _impl_.connect_info_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(ConnectPoorRes, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::rpc_server::ConnectInfo>()},
  }}, {{
    "\31\0\0\7\0\0\0\0"
    "rpc_server.ConnectPoorRes"
    "message"
  }},
};

::uint8_t* ConnectPoorRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.ConnectPoorRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // repeated .rpc_server.ConnectInfo connect_info = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_connect_info_size()); i < n; i++) {
    const auto& repfield = this->_internal_connect_info().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string message = 3;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.ConnectPoorRes.message");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.ConnectPoorRes)
  return target;
}

::size_t ConnectPoorRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.ConnectPoorRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .rpc_server.ConnectInfo connect_info = 2;
  total_size += 1UL * this->_internal_connect_info_size();
  for (const auto& msg : this->_internal_connect_info()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string message = 3;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ConnectPoorRes::_class_data_ = {
    ConnectPoorRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ConnectPoorRes::GetClassData() const {
  return &_class_data_;
}

void ConnectPoorRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ConnectPoorRes*>(&to_msg);
  auto& from = static_cast<const ConnectPoorRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.ConnectPoorRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_connect_info()->MergeFrom(
      from._internal_connect_info());
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConnectPoorRes::CopyFrom(const ConnectPoorRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.ConnectPoorRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConnectPoorRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ConnectPoorRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ConnectPoorRes::InternalSwap(ConnectPoorRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.connect_info_.InternalSwap(&other->_impl_.connect_info_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata ConnectPoorRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[5]);
}
// ===================================================================

class ConnectInfo::_Internal {
 public:
};

ConnectInfo::ConnectInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.ConnectInfo)
}
inline PROTOBUF_NDEBUG_INLINE ConnectInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : address_(arena, from.address_),
        _cached_size_{0} {}

ConnectInfo::ConnectInfo(
    ::google::protobuf::Arena* arena,
    const ConnectInfo& from)
    : ::google::protobuf::Message(arena) {
  ConnectInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.port_ = from._impl_.port_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.ConnectInfo)
}
inline PROTOBUF_NDEBUG_INLINE ConnectInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        _cached_size_{0} {}

inline void ConnectInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.port_ = {};
}
ConnectInfo::~ConnectInfo() {
  // @@protoc_insertion_point(destructor:rpc_server.ConnectInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ConnectInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ConnectInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.ConnectInfo)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _impl_.port_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ConnectInfo::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> ConnectInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ConnectInfo_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConnectInfo, _impl_.port_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectInfo, _impl_.port_)}},
    // string address = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectInfo, _impl_.address_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string address = 1;
    {PROTOBUF_FIELD_OFFSET(ConnectInfo, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 port = 2;
    {PROTOBUF_FIELD_OFFSET(ConnectInfo, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\26\7\0\0\0\0\0\0"
    "rpc_server.ConnectInfo"
    "address"
  }},
};

::uint8_t* ConnectInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.ConnectInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string address = 1;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.ConnectInfo.address");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 port = 2;
  if (this->_internal_port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_port(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.ConnectInfo)
  return target;
}

::size_t ConnectInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.ConnectInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string address = 1;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  // int32 port = 2;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ConnectInfo::_class_data_ = {
    ConnectInfo::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ConnectInfo::GetClassData() const {
  return &_class_data_;
}

void ConnectInfo::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ConnectInfo*>(&to_msg);
  auto& from = static_cast<const ConnectInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.ConnectInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConnectInfo::CopyFrom(const ConnectInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.ConnectInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ConnectInfo::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ConnectInfo::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ConnectInfo::InternalSwap(ConnectInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
        swap(_impl_.port_, other->_impl_.port_);
}

::google::protobuf::Metadata ConnectInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[6]);
}
// ===================================================================

class HeartbeatReq::_Internal {
 public:
};

HeartbeatReq::HeartbeatReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.HeartbeatReq)
}
inline PROTOBUF_NDEBUG_INLINE HeartbeatReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : address_(arena, from.address_),
        port_(arena, from.port_),
        _cached_size_{0} {}

HeartbeatReq::HeartbeatReq(
    ::google::protobuf::Arena* arena,
    const HeartbeatReq& from)
    : ::google::protobuf::Message(arena) {
  HeartbeatReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.server_type_ = from._impl_.server_type_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.HeartbeatReq)
}
inline PROTOBUF_NDEBUG_INLINE HeartbeatReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        port_(arena),
        _cached_size_{0} {}

inline void HeartbeatReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.server_type_ = {};
}
HeartbeatReq::~HeartbeatReq() {
  // @@protoc_insertion_point(destructor:rpc_server.HeartbeatReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HeartbeatReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.port_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void HeartbeatReq::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.HeartbeatReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _impl_.port_.ClearToEmpty();
  _impl_.server_type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HeartbeatReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2> HeartbeatReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HeartbeatReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .rpc_server.ServerType server_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HeartbeatReq, _impl_.server_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(HeartbeatReq, _impl_.server_type_)}},
    // string address = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(HeartbeatReq, _impl_.address_)}},
    // string port = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(HeartbeatReq, _impl_.port_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .rpc_server.ServerType server_type = 1;
    {PROTOBUF_FIELD_OFFSET(HeartbeatReq, _impl_.server_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string address = 2;
    {PROTOBUF_FIELD_OFFSET(HeartbeatReq, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string port = 3;
    {PROTOBUF_FIELD_OFFSET(HeartbeatReq, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\7\4\0\0\0\0"
    "rpc_server.HeartbeatReq"
    "address"
    "port"
  }},
};

::uint8_t* HeartbeatReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.HeartbeatReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_server_type(), target);
  }

  // string address = 2;
  if (!this->_internal_address().empty()) {
    const std::string& _s = this->_internal_address();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.HeartbeatReq.address");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string port = 3;
  if (!this->_internal_port().empty()) {
    const std::string& _s = this->_internal_port();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.HeartbeatReq.port");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.HeartbeatReq)
  return target;
}

::size_t HeartbeatReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.HeartbeatReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string address = 2;
  if (!this->_internal_address().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_address());
  }

  // string port = 3;
  if (!this->_internal_port().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_port());
  }

  // .rpc_server.ServerType server_type = 1;
  if (this->_internal_server_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_server_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HeartbeatReq::_class_data_ = {
    HeartbeatReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* HeartbeatReq::GetClassData() const {
  return &_class_data_;
}

void HeartbeatReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HeartbeatReq*>(&to_msg);
  auto& from = static_cast<const HeartbeatReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.HeartbeatReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (!from._internal_port().empty()) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_server_type() != 0) {
    _this->_internal_set_server_type(from._internal_server_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HeartbeatReq::CopyFrom(const HeartbeatReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.HeartbeatReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HeartbeatReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* HeartbeatReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void HeartbeatReq::InternalSwap(HeartbeatReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.port_, &other->_impl_.port_, arena);
  swap(_impl_.server_type_, other->_impl_.server_type_);
}

::google::protobuf::Metadata HeartbeatReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[7]);
}
// ===================================================================

class HeartbeatRes::_Internal {
 public:
};

HeartbeatRes::HeartbeatRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rpc_server.HeartbeatRes)
}
inline PROTOBUF_NDEBUG_INLINE HeartbeatRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

HeartbeatRes::HeartbeatRes(
    ::google::protobuf::Arena* arena,
    const HeartbeatRes& from)
    : ::google::protobuf::Message(arena) {
  HeartbeatRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:rpc_server.HeartbeatRes)
}
inline PROTOBUF_NDEBUG_INLINE HeartbeatRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void HeartbeatRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
HeartbeatRes::~HeartbeatRes() {
  // @@protoc_insertion_point(destructor:rpc_server.HeartbeatRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void HeartbeatRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void HeartbeatRes::Clear() {
// @@protoc_insertion_point(message_clear_start:rpc_server.HeartbeatRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* HeartbeatRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> HeartbeatRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HeartbeatRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(HeartbeatRes, _impl_.message_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HeartbeatRes, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(HeartbeatRes, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(HeartbeatRes, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(HeartbeatRes, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\7\0\0\0\0\0"
    "rpc_server.HeartbeatRes"
    "message"
  }},
};

::uint8_t* HeartbeatRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rpc_server.HeartbeatRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rpc_server.HeartbeatRes.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rpc_server.HeartbeatRes)
  return target;
}

::size_t HeartbeatRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rpc_server.HeartbeatRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData HeartbeatRes::_class_data_ = {
    HeartbeatRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* HeartbeatRes::GetClassData() const {
  return &_class_data_;
}

void HeartbeatRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<HeartbeatRes*>(&to_msg);
  auto& from = static_cast<const HeartbeatRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rpc_server.HeartbeatRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HeartbeatRes::CopyFrom(const HeartbeatRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rpc_server.HeartbeatRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool HeartbeatRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* HeartbeatRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void HeartbeatRes::InternalSwap(HeartbeatRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata HeartbeatRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_server_5fcentral_2eproto_getter, &descriptor_table_server_5fcentral_2eproto_once,
      file_level_metadata_server_5fcentral_2eproto[8]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace rpc_server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
