// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_gateway.proto

#include "server_gateway.pb.h"
#include "server_gateway.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace rpc_server {

static const char* GatewayServer_method_names[] = {
  "/rpc_server.GatewayServer/RequestForward",
};

std::unique_ptr< GatewayServer::Stub> GatewayServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GatewayServer::Stub> stub(new GatewayServer::Stub(channel, options));
  return stub;
}

GatewayServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestForward_(GatewayServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GatewayServer::Stub::RequestForward(::grpc::ClientContext* context, const ::rpc_server::ForwardRequest& request, ::rpc_server::ForwardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::rpc_server::ForwardRequest, ::rpc_server::ForwardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestForward_, context, request, response);
}

void GatewayServer::Stub::async::RequestForward(::grpc::ClientContext* context, const ::rpc_server::ForwardRequest* request, ::rpc_server::ForwardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::rpc_server::ForwardRequest, ::rpc_server::ForwardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestForward_, context, request, response, std::move(f));
}

void GatewayServer::Stub::async::RequestForward(::grpc::ClientContext* context, const ::rpc_server::ForwardRequest* request, ::rpc_server::ForwardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestForward_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::rpc_server::ForwardResponse>* GatewayServer::Stub::PrepareAsyncRequestForwardRaw(::grpc::ClientContext* context, const ::rpc_server::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::rpc_server::ForwardResponse, ::rpc_server::ForwardRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestForward_, context, request);
}

::grpc::ClientAsyncResponseReader< ::rpc_server::ForwardResponse>* GatewayServer::Stub::AsyncRequestForwardRaw(::grpc::ClientContext* context, const ::rpc_server::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestForwardRaw(context, request, cq);
  result->StartCall();
  return result;
}

GatewayServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GatewayServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GatewayServer::Service, ::rpc_server::ForwardRequest, ::rpc_server::ForwardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GatewayServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::rpc_server::ForwardRequest* req,
             ::rpc_server::ForwardResponse* resp) {
               return service->RequestForward(ctx, req, resp);
             }, this)));
}

GatewayServer::Service::~Service() {
}

::grpc::Status GatewayServer::Service::RequestForward(::grpc::ServerContext* context, const ::rpc_server::ForwardRequest* request, ::rpc_server::ForwardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace rpc_server

